config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index", as: 'home'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :name, presence: true, length: {minimum: 3}
  validates :summary, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:title, :description, :status)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
   @post = Post.all
  end
  def new
   @post = Post.new
  end
  def show
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
    redirect_to @post
  else
    render 'edit'
  end
end
  def edit
    @post = Post.find(params[:id])
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  def create
    @post = Post.new(post_params)
    if(@post.save)
    redirect_to @post
  else
    render 'new'
  end
  end
  private def post_params
    params.require(:post).permit(:name, :summary, :start_date,:exnd_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TryRuby</title>
    <%= csrf_meta_tags %>
<%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br><br>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <span class="navbar-brand">Try Ruby</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <span class="nav-link"><%= link_to "Main page", home_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "Create a project", new_post_path %></span>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "Exit", destroy_user_session_path, method: :delete %></span>
      </li>
      <% else %>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "Sign In", new_user_session_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "Sign Up", new_user_registration_path %></span>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
    <%= yield %>
    </div>

    <footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-muted">All rights reserved ;p</span>
      </div>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |err| %>
  <div class="alert alert-danger"><%= err %></div>
  <% end %>
  <% end %>
<p>
  <br>
  Name:<br><br>
  <%= f.text_field(:name, {:class => 'form-control'}) %>
</p>
<p>
   Summary: <br><br>
   <%= f.text_area(:summary, {:class => 'form-control'}) %>
 </p>
 <p>
   Start_date: <br><br>
   <%= f.date_field(:start_date, {:class => 'form-control'}) %>
   </p>
   <p>
     End_date: <br><br>
     <%= f.date_field(:exnd_date, {:class => 'form-control'})%>
     </p>
 <p>
   <%= f.submit ({:value => 'Save Project', :class => 'btn btn-success'})%>
 </p>
 <%end%>

app/views/posts/index.html.erb
<% @post.each do |post| %>
<div class="alert alert-light">
<hr>
 <h3>Project name: <%= post.name  %></h3>
 <p>Summary: <%= post.summary %></p>
  <p>Start_date: <%= post.start_date %></p>
   <p>End_date: <%= post.exnd_date %></p>
   <%= link_to "Details", post_path(post), :class => 'btn btn-outline-primary' %>
   <hr>
 </div>
   <% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |err| %>
  <div class="alert alert-danger"><%= err %></div>
  <% end %>
  <% end %>
<p>
  <br>
  Name:<br><br>
  <%= f.text_field(:name, {:class => 'form-control'}) %>
</p>
<p>
   Summary: <br><br>
   <%= f.text_area(:summary, {:class => 'form-control'}) %>
 </p>
 <p>
   Start_date: <br><br>
   <%= f.date_field(:start_date, {:class => 'form-control'}) %>
   </p>
   <p>
     End_date: <br><br>
     <%= f.date_field(:exnd_date, {:class => 'form-control'})%>
     </p>
 <p>
   <%= f.submit ({:value => 'Save Project', :class => 'btn btn-success'})%>
 </p>
 <%end%>

app/views/posts/show.html.erb
<br><br><br><br>
<h1>Project name: <%= @post.name %></h1>
<h1>Summary: <em><%= @post.summary %></em></h1>
<h1>Start_date: <%= @post.start_date %></h1>
<h1>End_date: <%= @post.exnd_date %></h1>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %>
<br><hr>
<h1>Tasks: </h1>
<% @post.comments.each do |comment| %>
<div class="alert alert-light">
<hr>
 <h3>Title: <%= comment.title %></h3>
 <p>Decription: <%= comment.description %></p>
  <p>Status: <%= comment.status %></p>
   <hr>
 </div>
   <% end %>

<hr>
<h1>Add task to project</h1>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
  <br>
  Task:<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
   Decription: <br>
   <%= f.text_area(:description, {:class => 'form-control'}) %>
 </p>
 <p>
   <b>Status: </b><br>
   <em>New: </em><%= f.text_field(:status, {:type => 'radio', :value => 'new'}) %><br>
   <em>In proggress: </em><%= f.text_field(:status, {:type => 'radio', :value => 'in progress'}) %><br>
   <em>Done: </em><%= f.text_field(:status, {:type => 'radio', :value => 'done'}) %>
   </p>
 <p>
   <%= f.submit ({:value => 'Add task to project', :class => 'btn btn-success'})%>
 </p>
 <%end%>